import {
  chooseDefaultOllamaModel,
  chooseGeneralOllamaModel,
  chooseThinkOllamaModel,
  detectOllamaModels,
  getRouterUrl,
  localEnvExampleFile,
  localEnvFile,
  localFirstEnvOrder,
  parseEnvFile,
  providerEnvFile,
  providerEnvOrder,
  writeEnvFile,
} from './local-first-utils.js'

const detectedModels = detectOllamaModels()
const defaultModel =
  chooseDefaultOllamaModel(detectedModels) ?? 'qwen2.5-coder:latest'
const thinkModel =
  chooseThinkOllamaModel(detectedModels, defaultModel) ??
  'qwen3-coder:latest'
const generalModel =
  chooseGeneralOllamaModel(detectedModels, [defaultModel, thinkModel]) ??
  'gemma4:31b'

const localEnv = {
  ...parseEnvFile(localEnvExampleFile),
  ...parseEnvFile(localEnvFile),
}

localEnv.CLAUDE_CODE_LOCAL_FIRST ??= '1'
localEnv.DISABLE_TELEMETRY ??= '1'
localEnv.CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC ??= '1'
localEnv.DISABLE_COST_WARNINGS ??= '1'
localEnv.ANTHROPIC_BASE_URL ??= getRouterUrl()
localEnv.ANTHROPIC_AUTH_TOKEN ??= 'local-router'
localEnv.API_TIMEOUT_MS ??= '600000'

const providerEnv = {
  ...parseEnvFile(providerEnvFile),
}
const legacyThinkLongContext = providerEnv.ROUTER_LONG_CONTEXT

providerEnv.OLLAMA_MODEL ??= defaultModel
providerEnv.OLLAMA_THINK_MODEL ??= thinkModel
providerEnv.OLLAMA_GENERAL_MODEL ??= generalModel
providerEnv.OPENAI_API_KEY ??= ''
providerEnv.OPENAI_MODEL ??= 'gpt-4.1-mini'
providerEnv.OPENAI_LONG_CONTEXT_MODEL ??= 'gpt-4.1'
providerEnv.DEEPSEEK_API_KEY ??= ''
providerEnv.DEEPSEEK_MODEL ??= 'deepseek-chat'
providerEnv.DEEPSEEK_REASONING_MODEL ??= 'deepseek-reasoner'
providerEnv.DASHSCOPE_API_KEY ??= ''
providerEnv.QWEN_MODEL ??= 'qwen3-coder-plus'
providerEnv.ROUTER_DEFAULT ??= `ollama,${providerEnv.OLLAMA_MODEL}`
providerEnv.ROUTER_BACKGROUND ??= `ollama,${providerEnv.OLLAMA_MODEL}`
providerEnv.ROUTER_THINK ??= `ollama,${providerEnv.OLLAMA_THINK_MODEL}`
if (
  !legacyThinkLongContext ||
  legacyThinkLongContext === `ollama,${providerEnv.OLLAMA_THINK_MODEL}` ||
  legacyThinkLongContext === 'ollama,qwen3-coder:latest'
) {
  providerEnv.ROUTER_LONG_CONTEXT = `ollama,${providerEnv.OLLAMA_GENERAL_MODEL}`
} else {
  providerEnv.ROUTER_LONG_CONTEXT = legacyThinkLongContext
}

writeEnvFile(localEnvFile, localEnv, localFirstEnvOrder, [
  'Generated by scripts/setup-local-first.ts',
  'Adjust ANTHROPIC_BASE_URL only if your local router listens elsewhere.',
])

writeEnvFile(providerEnvFile, providerEnv, providerEnvOrder, [
  'Generated by scripts/setup-local-first.ts',
  'Override provider keys here when you want hybrid routing.',
])

console.log(`Wrote ${localEnvFile}`)
console.log(`Wrote ${providerEnvFile}`)

if (detectedModels.length) {
  console.log(`Detected Ollama models: ${detectedModels.join(', ')}`)
  console.log(`Selected default model: ${providerEnv.OLLAMA_MODEL}`)
  console.log(`Selected think model: ${providerEnv.OLLAMA_THINK_MODEL}`)
  console.log(`Selected general model: ${providerEnv.OLLAMA_GENERAL_MODEL}`)
} else {
  console.log(
    'No local Ollama models were detected. The generated file keeps placeholder values until you pull a model.',
  )
}
